package com.nogemasa.weixin;


public interface WXGlobalConstant {
    String WX_SYS_BUSY = "-1";//系统繁忙
    String WX_SUCCESS_FLAG = "0";//系统繁忙
    String GET_ACCESS_ERROR = "40001";//获取access_token时AppSecret错误，或者access_token无效
    String WRONG_DOCUTYPE = "40002";// 不合法的凭证类型
    String WRONG_OPENID = "40003";//不合法的OpenID
    String WRONG_MEDIATYPE = "40004";//不合法的媒体文件类型
    String WRONG_TEXTTYPE = "40005";//不合法的文件类型
    String WRONG_TEXTSIZE = "40006";// 不合法的文件大小
    String WRONG_MEDIAID = "40007";// 不合法的媒体文件id
    String WRONG_MESSAGETYPE = "40008";//不合法的消息类型
    String WRONG_PICSIZE = "40009";//不合法的图片文件大小
    String WRONG_VOICESIZE = "40010";//不合法的语音文件大小
    String WRONG_VEDIOSIZE = "40011";//不合法的视频文件大小
    String WRONG_THUMBNAILSIZE = "40012";//不合法的缩略图文件大小
    String WRONG_OPPID = "40013";//不合法的APPID
    String WRONG_ACCESS_TOKEN = "40014";//不合法的access_token
    String WRONG_MENUTYPE = "40015";//不合法的菜单类型
    String WRONG_BTNNUM1 = "40016";//不合法的按钮个数
    String WRONG_BTNNUM2 = "40017";//不合法的按钮个数
    String WRONG_BTNNAME_LENGTH = "40018";//不合法的按钮名字长度
    String WRONG_BTNKEY_LENGTH = "40019";//不合法的按钮KEY长度
    String WRONG_BTNURL_LENGTH = "40020";//不合法的按钮URL长度
    String WRONG_SUBMENU_VERSIONNUM = "40021";//不合法的菜单版本号
    String WRONG_SUBMENU_GRADE = "40022";//不合法的子菜单级数
    String WRONG_SUBMENU_NUM = "40023";//不合法的子菜单按钮个数
    String WRONG_SUBMENU_TYPE = "40024";//不合法的子菜单按钮类型
    String WRONG_SUBMENU_NAMELENGTH = "40025";//不合法的子菜单按钮名字长度
    String WRONG_SUBMENU_KEYLENGTH = "40026";//不合法的子菜单按钮KEY长度
    String WRONG_SUBMENU_URLLENGTH = "40027";//不合法的子菜单按钮URL长度
    String WRONG_CUSTOMMENU_USER = "40028";//不合法的自定义菜单使用用户
    String WRONG_OAUTH_CODE = "40029";//不合法的oauth_code
    String WRONG_REFRESH_TOKEN = "40030";//不合法的refresh_token
    String WRONG_OPENID_LIST = "40031";//不合法的openid列表
    String WRONG_OPENID_LISTLENGTH = "40032";//不合法的openid列表长度
    String WRONG_REQ_CHAR = "40033";//不合法的请求字符，不能包含uxxxx格式的字符
    String WRONG_PARAMETER = "40035";//不合法的参数
    String WRONG_REQ_FORM = "40038";//不合法的请求格式
    String WRONG_URL_LENGTH = "40039";//不合法的URL长度
    String WRONG_GROUP_ID = "40050";//不合法的分组id
    String WRONG_GROUP_NAME = "40051";//分组名字不合法
    String LACK_ACCESSTOKEN = "41001";//缺少access_token参数
    String LACK_APPID = "41002";//缺少appid参数
    String LACK_REFRESHTOKEN = "41003";//缺少refresh_token参数
    String LACK_SECRET = "41004";//缺少secret参数
    String LACK_MEDIA_DATA = "41005";//缺少多媒体文件数据
    String LACK_MEDIA_ID = "41006";//缺少media_id参数
    String LACK_SUBMENU_DATA = "41007";//缺少子菜单数据
    String LACK_OAUTH_CODE = "41008";// 缺少oauth code
    String LACK_OPENID = "41009";//缺少openid
    String ACCESS_TOKEN_OVERTIME = "42001";//access_token超时
    String REFRESH_TOKEN_OVERTIME = "42002";//refresh_token超时
    String OAUTH_CODE_OVERTIME = "42003";//oauth_code超时
    String NEED_GET_REQ = "43001";//需要GET请求
    String NEED_POST_REQ = "43002";//需要POST请求
    String NEED_HTTPS_REQ = "43003";//需要HTTPS请求
    String NEED_RECEIVER_ATTENTION = "43004";//需要接收者关注
    String NEED_FRIEND = "43005";//需要好友关系
    String EMPTY_MEDIA = "44001";//多媒体文件为空
    String EMPTY_OPSTDATA = "44002";//POST的数据包为空
    String EMPTY_NEWS = "44003";//图文消息内容为空
    String EMPTY_TEXT = "44004";//文本消息内容为空
    String EXCEEDLIMIT_MEDIA_SIZE = "45001";//多媒体文件大小超过限制
    String EXCEEDLIMIT_MSG_CONT = "45002";//消息内容超过限制
    String EXCEEDLIMIT_HEADER_FIELD = "45003";//标题字段超过限制
    String EXCEEDLIMIT_DISCRIBE_FIELD = "45004";//描述字段超过限制
    String EXCEEDLIMIT_LINK_FIELD = "45005";//链接字段超过限制
    String EXCEEDLIMIT_IMGLINK_FIELD = "45006";//图片链接字段超过限制
    String EXCEEDLIMIT_VOICE_TIME = "45007";//语音播放时间超过限制
    String EXCEEDLIMIT_NEWS_MSG = "45008";//图文消息超过限制
    String EXCEEDLIMIT_INTERFACE_CALL = "45009";//接口调用超过限制
    String EXCEEDLIMIT_MENU_CREATE_NUM = "45010";//创建菜单个数超过限制
    String EXCEEDLIMIT_RESP_TIME = "45015";//回复时间超过限制
    String SYSGROUP_NOTALLOW_MODIFY = "45016";// 系统分组，不允许修改
    String GROUP_NAME_OVERLENGTH = "45017";//分组名字过长
    String GROUP_NUM_OVER = "45018";//分组数量超过上限
    String INEXISTENCE_MEDIA_DATA = "46001";//不存在媒体数据
    String INEXISTENCE_MENU_VERSION = "46002";//不存在的菜单版本
    String INEXISTENCE_MENU_DATA = "4003";//不存在的菜单数据
    String INEXISTENCE_USER = "46004";//不存在的用户
    String WRONG_ANALYSIS = "47001";//解析JSON/XML内容错误
    String UNAUTHORIZED_API = "48001";//api功能未授权
    String USER_UNAUTHORIZED_API = "50001";//用户未授权该api
}